#!/bin/bash
# Called whenever a new demo is put on screen
ROOT=$(cd $(dirname "$0") && pwd)

AUTHOR="${1}"
DEMO="${2}"

REPO=$(cd ${ROOT} && git config --get remote.origin.url)


echo ">< ${DEMO} >< by ${AUTHOR} >< ${REPO} ><" > /tmp/demo_data.txt

