#!/bin/bash

ROOT=$(cd $(dirname "$0") && pwd)
cd ${ROOT} || exit 1

git pull

for DEMO in ${ROOT}*/; do
  [ -d "${DEMO}" ] || continue

  [ -x "${DEMO}/Setup" ] || continue

  (
    cd "${DEMO}" &&
    ./Setup
  )
done

