#!/bin/bash

# Settings
TIMEOUT=${TIMEOUT:-60}


######



ROOT=$(cd $(dirname "$0") && pwd)
cd ${ROOT} || exit 1



# Make sure our starting state is fresh and clean
${ROOT}/refresh

while true; do

  # Refresh in the background while we're running
  ${ROOT}/refresh &
  REFRESH_PID=$!


  for DEMO in ${ROOT}/*/; do

    [ -x "${DEMO}/Boot" ] || continue

    AUTHOR=$(cd "${DEMO}" && git log -1 --pretty=%an)

    [ -r "${DEMO}/Credits" ] && AUTHOR=$(head -n 1 ${DEMO}/Credits)

    NAME=$(basename "${DEMO}")

    ${ROOT}/advertise "${AUTHOR}" "${NAME}"

    echo "Starting ${DEMO}"
    (cd "${DEMO}" && timeout --kill-after=${TIMEOUT} ${TIMEOUT} ./Boot)

  done


  # Hopefully, all demos are built by now
  wait $REFRESH_PID

done

